### ISSUE TITLE
Separate src/cut mesh individually after the Boolean operation

### ISSUE THREAD

**Issue by thunderbirdtr** [cutdigital/mcut#1]
Hello, I was trying to use mcut "CSGBoolean.cpp" operation in order to learn cutting but after the cut process complete I only wanna see "source mesh" not the "cut mesh",  after "cut" process complete I both cutted area and  cut mesh(depend on operation I can see different section cut mesh not entire cut mesh before cut) as well. Is there any way to separate them individually ?

Thank you.

**Comment by chitalu** [comment]
Hi @thunderbirdtr,

Thanks for using MCUT. 

> I only wanna see "source mesh" not the "cut mesh"

Do you mean 1) the exact source mesh that is provided as input to the `mcDispatch` function? or, 2) the output connected component(s) corresponding to the source mesh (sealed and/or unsealed) after cutting.  

> Is there any way to separate them individually ?

You can also filter the output connected components by using `mcGetConnectedComponents` and/or `mcGetConnectedComponentData`. The function `mcGetConnectedComponentData` allows you to query specific information about a connected component which is useful for determining e.g. whether it originated from the source-mesh or the cut-mesh.

Please provide screenshots (or a basic illustration) if possible. That's also helpful for conveying your problem.

- Floyd

**Comment by thunderbirdtr** [comment]
Hello, @chitalu  thanks for quick response,

![image](https://user-images.githubusercontent.com/1688848/145967310-20950305-e1e8-416d-8778-24fd22adcce8.png)

Blue mesh is my cut mesh and after I cut with it.


![image](https://user-images.githubusercontent.com/1688848/145967629-a2499fad-acdc-4445-9480-4f896e2653f4.png)

I have mesh after cut process done area pointing via arrow but I don't wanna see "cut mesh" at all. 

Blue is mesh "hollow" from inside so it is not solid, I extrude with from spline

**Comment by chitalu** [comment]
I understand. The solution is:

1. Use the flag `MC_DISPATCH_FILTER_PATCH_OUTSIDE` when you call the `mcDispatch` function, which must be specified together with `MC_DISPATCH_VERTEX_ARRAY_[DOUBLE or FLOAT]`. It is generally recommended to also include the flag `MC_DISPATCH_ENFORCE_GENERAL_POSITION`. See the documentation for further information.
2. Use the flag `MC_CONNECTED_COMPONENT_TYPE_PATCH` when calling the function `mcGetConnectedComponents`.  

`MC_DISPATCH_FILTER_PATCH_OUTSIDE` is required because the type of connected component you desire is a patch from the cut-mesh, which lies 'outside'--or in this case, 'above'--the source mesh as determined by the polygon winding order (direction of normals) on the source mesh.

**Comment by thunderbirdtr** [comment]
I wanna try this solution but there is one more problem, I'm generating that cut mesh via "opencascade kernel" and convert into Eigen matrix then convert that values into mcut variables and start cut process but fail with error code "-4". If I use same mesh but open via "obj" file and ask cut again it works,  I checked "faces and vertex numbers"  all matched, file content also matched. I don't understand why is that giving me error.  I also notice that "libigl obj write is change the position of current mesh but "saving as a "stl" is keeping the position of the mesh.  because of that change also can make an issue as well. Because If the position is change and can't touch mesh, makes not good result as well.

**Comment by chitalu** [comment]
Hi,

Please confirm whether the original problem has been resolved so that this issue can be marked as resolved.

- Floyd

**Comment by thunderbirdtr** [comment]
I was able to cut with proper OBJ files and got only inside and only outside of the mesh yes +1
