### ISSUE TITLE
Missing triangles

### ISSUE THREAD

**Issue by 24THEGuNNeR07** [cutdigital/mcut#11]
Hi,

I'm trying some operations on meshes with around 6k vertices and I often receive components with missing faces like on SS:
![example](https://user-images.githubusercontent.com/31591820/200011096-4c21e433-344a-4294-9e67-4685ac048311.png)
Just wanted to ask if this bugs are included or can I fix it somehow with your API ?

Regards

**Comment by chitalu** [comment]
Hi @24THEGuNNeR07 

I cannot diagnose your problem without knowing about your inputs. Please provide them together with your dispatch flags.

**Comment by 24THEGuNNeR07** [comment]
Hi @chitalu 

Sure ! Here is zip file with source and cut meshes. Actually I'm using BasicCmdLineApp without any changes on dispatch flags. The only change I made is resizing cut mesh rigth after reading it to cut source into some parts (adding loading part code as well). [](url)
[meshes.zip](https://github.com/cutdigital/mcut/files/9950333/meshes.zip)

```
// load meshes
    // -----------
    std::vector<double> srcMeshVertices;
    std::vector<uint32_t> srcMeshFaceIndices;
    std::vector<uint32_t> srcMeshFaceSizes;
    readMesh(srcMeshFilePath, srcMeshVertices, srcMeshFaceIndices, srcMeshFaceSizes);

    printf("src-mesh vertices=%d faces=%d\n", (int)srcMeshVertices.size()/3, (int)srcMeshFaceSizes.size());

    std::vector<double> cutMeshVertices;
    std::vector<uint32_t> cutMeshFaceIndices;
    std::vector<uint32_t> cutMeshFaceSizes;
    readMesh(cutMeshFilePath, cutMeshVertices, cutMeshFaceIndices, cutMeshFaceSizes);

    for (int i = 0; i < cutMeshVertices.size(); i++) {
        cutMeshVertices[i] = cutMeshVertices[i] * 3.0;
    }
```

**Comment by chitalu** [comment]
This is a bug.

A temporary workaround is to query non-triangulated faces (post-dispatch), and then do you own triangulation. You can query non-triangulated faces by passing `MC_CONNECTED_COMPONENT_DATA_FACE` to `mcGetConnectedComponentData`. You may also refer to the `HelloWorld` tutorial for an example of how to do this.
 
Shall try to fix this in due course.

**Comment by 24THEGuNNeR07** [comment]
Thank you for quick answer !

**Comment by chitalu** [comment]
[the-gunner.zip](https://github.com/cutdigital/mcut/files/10271900/the-gunner.zip)

This issue has now been resolved. I am attaching the files that I produced with the BasicCmdLineApp tutorial (tweaked with the same scaling modification as you had used). Changes are currently on [cdt](https://github.com/cutdigital/mcut/commit/f25fc9bc1580ea3a64537b408c2901f92bee517e) branch and will be merged with master after further testing.

![image](https://user-images.githubusercontent.com/7461679/208752367-386d1074-d374-4d42-880d-c7cb20dc685c.png)
