### ISSUE TITLE
Memory Explosion

### ISSUE THREAD

**Issue by abetusk** [cutdigital/mcut#14]
Attached are two files that cause the memory to explode when using the `CSGBoolean` tool to do an "A-B" operation.

Here is the invocation:

```
./CSGBoolean cur.off pill17.off -ds
```

I am trying to subtract a "pill" shape from a "cylinder" shape.

| cylinder | pill | cylinder and pill |
|---|---|---|
| ![snapshot00](https://user-images.githubusercontent.com/1406122/207337756-da71c48e-cff5-409d-9d8b-826c18065f69.png) | ![snapshot01](https://user-images.githubusercontent.com/1406122/207337854-368b23b7-d2f4-4704-ab9a-1c51bbe36977.png) | ![snapshot02](https://user-images.githubusercontent.com/1406122/207338188-bd779021-c24c-4aca-ab07-242b128e395c.png) |

note that I'm trying to subtract the "pill" from the cylinder, so this picture is only showing the representation of them together for clarity

Here is a ZIP file with `cur.off` and `pill17.off` as listed in the above `CSGBoolean` invocation:

[mcut_mem_explode_a_m_b.zip](https://github.com/cutdigital/mcut/files/10218421/mcut_mem_explode_a_m_b.zip)

There could well be a problem with my geometry but, as far as I can tell, it's fine. I'm trying to construct a column with groves in it by subtracting out "pill" shapes. When I take the base cylinder and subtract just the `pill17.off` geometry, it works just fine. When I subtract off the pill shapes before trying to subtract `pill17.off`, the memory usage explodes and quickly fills 8GB+.

Any suggestions on why this might be occurring would be welcome.

**Comment by chitalu** [comment]
Hi @abetusk 

`cur.off` contains at least one face with zero area. Fix it the the library should run fine. MCUT requires that (intersecting) faces have non-zero area.
