### ISSUE TITLE
HelloWorld tutorial segfaults when built with multi-threading 

### ISSUE THREAD

**Issue by dflarson** [cutdigital/mcut#16]
When mcut is built with multi-threading (which is off by default) the HelloWorld example segfaults. The other tutorials execute as expected. Do you have any insight as to why this program's inputs are causing this issue?

Thanks - great library by the way!

**Comment by chitalu** [comment]
Hi, 

This should now be [resolved](https://github.com/cutdigital/mcut/commit/25de1f80392d972f4c7ad1e247c33f847cbb9792). Will be merged into master in due course.
