### ISSUE TITLE
Faces with more than 3 vertices don't work

### ISSUE THREAD

**Issue by brunnerant** [cutdigital/mcut#17]
I have tested your library, and it looks great ! Only issue is that I'm not able to cut meshes that contain faces with more than 3 vertices, and the library outputs that there is no components. Is this a known issue ? Because I saw in `tutorials/HelloWorld/HelloWorld.cpp` a line marked with "triangulation bug"...

I can give you more details about my particular case if you want :).

Thanks for your help !

**Comment by chitalu** [comment]
Hi @brunnerant 

> I can give you more details about my particular case if you want

Yes, that would be helpful.
