### ISSUE TITLE
Get triangulation face map

### ISSUE THREAD

**Issue by brunnerant** [cutdigital/mcut#18]
Hello,

Using `MC_CONNECTED_COMPONENT_DATA_FACE_MAP`, it is possible to map from output faces to the corresponding faces from the input meshes. I was wondering if it is possible to do the same thing with the triangulated faces ? That is, would it be possible to know, for each triangle of the output mesh, from which input face it originates ?

Thanks for your help !

**Comment by chitalu** [comment]
Hi @brunnerant,

> would it be possible to know, for each triangle of the output mesh, from which input face it originates ?

Yes. You can instead use `MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION_MAP`.

**Comment by chitalu** [comment]
done.
