### ISSUE TITLE
tutorials error and other bugs

### ISSUE THREAD

**Issue by prashant-saxena** [cutdigital/mcut#19]
Hi,
The three tutorials are producing errors:
```
VertexNormals >> MCUT error: faceVertexOffset != -1
TextureCoordinates >> MCUT error: faceVertexOffset != -1
FaceNormals >> MCUT error: faceVertexOffset != -1
```
I have tested on several other meshes but most of the time mcut is ending up with some message. There are two meshes in the attached zip file.  The csgboolean.cpp is producing this error:

csgboolean.exe source.obj cutter.obj -i

or 

csgboolean.exe source.obj cutter.obj -ds
```
compute INTERSECTION
operator()(...) -> max perturbation iteratons reached (EventID=00000000000decb0)
MCUT error: err == MC_NO_ERROR
```
Although when working it's producing a very fine cut that's why I'm interested in this library. 

Cheers
[data.zip](https://github.com/cutdigital/mcut/files/11238459/data.zip)

**Comment by chitalu** [comment]
The vertices defining some (or possibly all) of your faces are _not_ coplanar. See for example the vertices defining face 0 of `source.obj'. 

Either make sure your quad-face vertices are coplanar, or consider converting to triangle meshes.
