### ISSUE TITLE
Fix to comply with CDT's license

### ISSUE THREAD

**Issue by artem-ogre** [cutdigital/mcut#20]
This repository contains modified code from [CDT library](https://github.com/artem-ogre/CDT) in [internal/cdt](https://github.com/cutdigital/mcut/tree/master/include/mcut/internal/cdt).
CDT is distributed under [MPL-2 license](https://www.mozilla.org/en-US/MPL/2.0/) and it is possible to [use it in the GPL project](https://www.gnu.org/licenses/license-list.html#MPL-2.0).

The current usage however is not complying with MPL-2.0.

To fix this I suggest:
- return the original license headers with the following text:
```
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
```
- put CDT `LICENSE` file into `internal/cdt` folder

Optionally, it would be nice to have an attribution and clarification that some files are dual-licensed.
The text could be:
```
This software is based part on CDT (C++ library for constrained Delaunay triangulation): 
https://github.com/artem-ogre/CDT
Copyright © 2019 Leica Geosystems Technology AB
Copyright © The CDT Contributors
Files that were originally under the MPL-2.0 are dual licensed under the MPL-2.0 and the GNU General Public License (GPL) licenses.
```

Please also note that even commercial users must comply with the license if they introduce further modifications to these files or distribute binaries (see Q8 in the [MPL-2.0 FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)).

**Comment by chitalu** [comment]
Hi @artem-ogre,

Thanks for the notification. 

I will do that, and close the issue once done.

Floyd

**Comment by artem-ogre** [comment]
Thank you for such a prompt fix, Floyd!
