### ISSUE TITLE
Non-Manifold and Multiple Connected Components limit

### ISSUE THREAD

**Issue by TualK** [cutdigital/mcut#21]
Hello,
I have a question concerning the future of MCUT.

I want to cut a shape with non-manifold parts and multiples connected components. 
I understand that, at the moment, MCUT isn't made to work in these cases.

Do you plan to remove these constraints in a future version of MCUT ?

Thanks !

**Comment by chitalu** [comment]
Hi @TualK 

There are no plans for such extensions to MCUT. 

- Floyd
