### ISSUE TITLE
mcDispatch returns error code -4 after importing stl file data

### ISSUE THREAD

**Issue by BombSky** [cutdigital/mcut#26]
In my project, I also used the open source library curaEngine. I used this open source library to import stl files for slicing and other operations without encountering any problems. But when I converted the grid model in curaEngine to mcut for Boolean operations, mcDispatch reported the error "An invalid value has been passed to the API." This passage was translated by Google. I don’t understand English. Please forgive me for any grammatical errors.
`
void CURAMesh2CutMes(cura::Mesh& CMesh, InputMesh &cutMesh)
{
    cutMesh.vertexCoordsArray = new std::vector<float>(CMesh.vertices.size() * 3);
    cutMesh.faceIndicesArray  = new std::vector<uint32_t>(CMesh.faces.size() * 3);
    cutMesh.faceSizesArray    = new std::vector<uint32_t>(CMesh.faces.size(), 3);
    for (size_t vertIndex = 0; vertIndex < CMesh.vertices.size(); vertIndex++)
    {
        cutMesh.vertexCoordsArray->at(vertIndex * 3 + 0) = (float)INT2MM(CMesh.vertices[vertIndex].p.x);
        cutMesh.vertexCoordsArray->at(vertIndex * 3 + 1) = (float)INT2MM(CMesh.vertices[vertIndex].p.y);
        cutMesh.vertexCoordsArray->at(vertIndex * 3 + 2) = (float)INT2MM(CMesh.vertices[vertIndex].p.z);
    }
    for (size_t meshindex = 0; meshindex < CMesh.faces.size(); meshindex++)
    {
        cutMesh.faceIndicesArray->at(meshindex * 3 + 0) = CMesh.faces[meshindex].vertex_index[0];
        cutMesh.faceIndicesArray->at(meshindex * 3 + 1) = CMesh.faces[meshindex].vertex_index[1];
        cutMesh.faceIndicesArray->at(meshindex * 3 + 2) = CMesh.faces[meshindex].vertex_index[2];
    }
}
`

**Comment by chitalu** [comment]
Can you share the output of mcut when run with a debug context?

**Comment by chitalu** [comment]
I am closing this issue due to a lack of response.
