### ISSUE TITLE
Question: mesh description

### ISSUE THREAD

**Issue by lvjonok** [cutdigital/mcut#28]
Hello! I have a question regarding mesh definition. Would it be a problem for the library with repeating vertices in input meshes?

In my situation there is such mesh description: Triangles -> Triangle -> Point -> floats. Meaning I do not know directly which points are repeating. However in your library it might not work if I just put everything with repetitions. Could you clarify this situation?

**Comment by chitalu** [comment]
Hi @lvjonok 

> Would it be a problem for the library with repeating vertices in input meshes?

Each input mesh must be a 2-manifold mesh, representing a single connected component. Each edge of this mesh must be used by at most two faces. Zero-length edges (and hence zero-area faces) are not allowed.

You may also refer to the FAQ [here](https://cutdigital.github.io/mcut.site/faq/).
