### ISSUE TITLE
Cut a cube with a cube

### ISSUE THREAD

**Issue by HerveRV** [cutdigital/mcut#29]
Hi ! I don't know how to do that :

I take 2 real cubes, withs TexUV, and normals, not 8 vertex but 24, and i try to start playing with that library
i use triangles, so sizefaces are only filled with 3

mcDispatch -> -4

->mcDebugMessageCallback + mcDebugMessageControl(context, McDebugSource::MC_DEBUG_SOURCE_ALL, McDebugType::MC_DEBUG_TYPE_ALL, McDebugSeverity::MC_DEBUG_SEVERITY_ALL, true);

print me that :
MCUT[0:0000000000000000,API:ERROR:HIGH:52] Detected multiple connected components in mesh (N=6)

ok, so i understand that the error say that the 6 faces are independant, and it need to be only 1. but they are not (independent by index, joined by real 3D position)
how can i succeed ?

**Comment by chitalu** [comment]
Hi @HerveRV 

> not 8 vertex but 24

This is your problem.

Specify your cube with a list of 8 vertices, and define your faces/triangles by having their indices reference this list.
