### ISSUE TITLE
Mesh cutting with plane

### ISSUE THREAD

**Issue by yvanblanchard** [cutdigital/mcut#3]
Hello,
I woulld like to start testing your lib with a sample mesh (closed volume) / plane intersection, and get the slice (2D) mesh as result, and the boundary as IGES (or at least as a list of points).
Is it already possible, and if yes how ?

Thank you.

**Comment by chitalu** [comment]
Hi @yvanblanchard 

Yes, this is already possible. 

One example of how to do this can be found in the "HelloWorld" tutorial, which is described [here](https://cutdigital.github.io/mcut.site/tutorials/helloWorld/).

You may also setup your meshes to be aligned as you require and intersect/cut with them using the "BasicCmdLineApp" tutorial. The .obj file format is assumed for your input meshes.

You will find the source code for these referenced tutorials in the "mcut/tutorials/" directory.

**Comment by yvanblanchard** [comment]
Thank you for your reply.
Sorry, my question was not enough clear ; I expected to define one of the reference plane (from input mesh) as cutting element (XY, XZ, YZ) ; it is not a big deal to build it using two triangles, but I need to size it to be sure that intersection exists with input mesh (need a piece of code..)

**Comment by chitalu** [comment]
According to my understanding, you would like to define an appropriate scale of a plane (e.g. spanned by either the XY, XZ, or YZ axis pairs), where this scale is large enough to ensure that this plane will intersect (or "slice") your input mesh. 

Is this a correct interpretation? If so, then your question is beyond the scope of MCUT, which assumes that the input meshes that you wish to intersect are well placed for there to be a cut.

**Comment by yvanblanchard** [comment]
Understood. 
Thank you for your help
