### ISSUE TITLE
TextureCoordinates instance running abnormally in MCUT V1.2.0.

### ISSUE THREAD

**Issue by xueyuanhong** [cutdigital/mcut#37]
TextureCoordinates instance running abnormally in MCUT V1.2.0.
TextureCoordinates instance  can run normally in MCUT V1.1.0.

**Comment by chitalu** [comment]
Hi @xueyuanhong,

Do you have an example image?

**Comment by xueyuanhong** [comment]
Screenshot of running results（TextureCoordinates instance running abnormally in MCUT V1.2.0）：

![TextureCoordinates](https://github.com/cutdigital/mcut/assets/12182430/214d28e2-8c86-463e-8263-1ed7575bfab9)

**Comment by xueyuanhong** [comment]
Screenshot of running results(TextureCoordinates instance running abnormally in MCUT V1.2.0)：
![TextureCoordinates](https://github.com/cutdigital/mcut/assets/12182430/bcb6561a-0fbb-4993-82a6-eacff936a771)

**Comment by xueyuanhong** [comment]
Screenshot of running results(TextureCoordinates instance can run normally in MCUT V1.1.0)：

![TextureCoordinatesV1 1_1](https://github.com/cutdigital/mcut/assets/12182430/ff47be29-2ea9-446f-9862-9058ebbbe348)
![TextureCoordinatesV1 1_2](https://github.com/cutdigital/mcut/assets/12182430/ef23bd61-8d5e-4224-888c-7cd6624829d3)
![TextureCoordinatesV1 1_3](https://github.com/cutdigital/mcut/assets/12182430/9ff709f5-a3f2-4c51-ba20-6537fdd604d2)

**Comment by chitalu** [comment]
Hi @xueyuanhong 

Is your problem simply that 1) the output being shown in the terminal/console is different between V1.2.0 and V1.1.0, or 2) that the texture coordinates that are propagated from the input meshes and onto the output connected components (computed by MCUT) are incorrect?

**Comment by chitalu** [comment]
This issue is now resolved on latest version (1.3.0).
