### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by lvjonok** [cutdigital/mcut#38]
Good day!

I have the following error: `mcut/source/frontend.cpp, 2932 at 'untraversed_adj_seam_vertex_count <= 1'` after running tutorial code `QuerySeamVerticesSorted`. I am not sure what is going wrong. Files I used are attached below, note that I have changed their extension to upload.

Moreover, this problem occurs with original files too.

[cutMesh.txt](https://github.com/cutdigital/mcut/files/13716715/cutMesh.txt)
[mesh.txt](https://github.com/cutdigital/mcut/files/13716716/mesh.txt)

**Comment by chitalu** [comment]
Hi @lvjonok 

Thanks. This seems like a bug.

**Comment by lvjonok** [comment]
Hello!

What do you think of such temporary fix:

```c++
// MCUT_ASSERT(untraversed_adj_seam_vertex_count <= 1);
if (untraversed_adj_seam_vertex_count > 1) continue;
```

Will it work somehow or failing assertion here is a crucial problem?

**Comment by chitalu** [comment]
Simply commenting out the line does the job. This will be available in the next release.
