### ISSUE TITLE
Debugging invalid source-mesh connectivity

### ISSUE THREAD

**Issue by FreakTheMighty** [cutdigital/mcut#41]
I'm attempting to read in a mesh from the attached Duck.glb and then cut it with a box. When I run `mcDispatch` I get an error complaining that `Debugging invalid source-mesh connectivity`. I believe I've traced it back more specifically to this check in `check_input_mesh`.

> Detected multiple connected components in mesh (N=10)

I'm not clear on what this is telling me. One thought I had was to import the glb into Blender and merge vertices by distance, in case there were multiple disconnected components in the mesh. This did in fact remove some vertices, but I get the same error. Furthermore, I don't see obviously disconnected components in the model.

Any pointers for how to proceed would be much appreciated.
 
[Duck.glb.zip](https://github.com/cutdigital/mcut/files/13909046/Duck.glb.zip)

**Comment by chitalu** [comment]
I recommend you use Meshlab to (visually) identify the connected components in your mesh. This should be a more direct way of solving your issue.
