### ISSUE TITLE
Integration with Unity Game Engine?

### ISSUE THREAD

**Issue by alimardanov** [cutdigital/mcut#44]
I want to use this library in Untiy Game Engine. There are several slicing functionality that we have to implement in our upcoming projects. I wonder if is it possible to convert this project into DLL file and call its methods from Unity C#? I could not get me head around on this as I am new to c++.

**Comment by IbrahimAkil96** [comment]
Yes, you can convert a C++ project into a DLL and call its methods from Unity using C#.

1. Create a C++ DLL
Set Up a New C++ Project:

Open Visual Studio and create a new project. Choose "Dynamic Link Library (DLL)" as the project type.
Write Your C++ Code:

Implement the slicing functionality and ensure you expose the functions you want to call from Unity. Use extern "C" to prevent name mangling.

![1](https://github.com/user-attachments/assets/bbc1780b-2108-4fc2-9bea-5eb1ba72bfa4)
![2](https://github.com/user-attachments/assets/36ed8761-24c7-43d7-bb63-19de1d7a65be)
![3](https://github.com/user-attachments/assets/3cff4b00-6a62-42ef-a1f2-31d3a007b5f0)
