### ISSUE TITLE
Crash when an edge intersects with another edge exactly

### ISSUE THREAD

**Issue by BluEgo** [cutdigital/mcut#48]
In kernel.cpp, I often hit this line, when meshes are not triangulated:

```cpp
// edge-case scenario: an edge intersects with another edge exactly
MCUT_ASSERT((int)intersection_test_ivtx_list.size() >= 2); 
```

I've attached a zip file containing 4 meshes:
- _meshA.obj_ and _meshB.obj_
- _triangleMeshA.obj_ and _triangleMeshB.obj_

The first couple are a cube and a lowres quad ball sphere, where every face is a quad.
The second couple contains exactly the same meshes, but triangulated.

In the first case, MCUT will assert, while the second will work without an issue.

[SimpleMeshes.zip](https://github.com/user-attachments/files/16917334/SimpleMeshes.zip)

**Comment by chitalu** [comment]
meshB.obj has non-planar faces. all faces need to be planar.
