### ISSUE TITLE
Always getting no connected components found using BasicCmdLineApp

### ISSUE THREAD

**Issue by FrankEscobar** [cutdigital/mcut#6]
[twoobjs.zip](https://github.com/cutdigital/mcut/files/9033600/twoobjs.zip)
As basic test I was trying to substract Sub0.obj from Box.obj.

I've tried with other files but without luck, btw I made them in Blender.

**Comment by chitalu** [comment]
Hi @FrankEscobar 

MCUT will partition a mesh by severing its edges with the faces of the other (e.g. the source-mesh is cut by ensuring its edges intersect cut-mesh faces). Your meshes do not intersect at all--hence "no connected components found".

![image](https://user-images.githubusercontent.com/7461679/177135568-0c0de785-1024-4415-a0cf-884e6840a2c3.png)

"Sub0" is located inside "Box"
