### ISSUE TITLE
Cannot Find Enum Member

### ISSUE THREAD

**Issue by chaojian-zhang** [cutdigital/mcut#7]
I was looking at the [tutorial](https://cutdigital.github.io/mcut.site/tutorials/helloWorld/):

![image](https://user-images.githubusercontent.com/7077098/188322933-96fd7ff8-e98d-4010-ab4f-40806a1a8522.png)

however when I try to reference it in code I found this:

```c
typedef enum McConnectedComponentData {
    //MC_CONNECTED_COMPONENT_DATA_VERTEX_COUNT = (1 << 0), /**< Number of vertices. */
    MC_CONNECTED_COMPONENT_DATA_VERTEX_FLOAT = (1 << 1), /**< List of vertex coordinates as an array of 32 bit floating-point numbers. */
    MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE = (1 << 2), /**< List of vertex coordinates as an array of 64 bit floating-point numbers. */
    //MC_CONNECTED_COMPONENT_DATA_FACE_COUNT = (1 << 4), /**< Number of faces. */
    MC_CONNECTED_COMPONENT_DATA_FACE = (1 << 5), /**< List of faces as an array of indices. */
```

I wonder why is `MC_CONNECTED_COMPONENT_DATA_VERTEX_COUNT ` commented out? Similarly, `MC_CONNECTED_COMPONENT_DATA_FACE_COUNT` is commented out as well.

**Comment by chitalu** [comment]
Hi @chaojian-zhang 

Thanks for your question.

The tutorial page is a little outdated. The flag has been deprecated because it is redundant. Moreover, you can infer the number of vertices from the data type that is used to represent the vertex coordinates being queried: 

```c++
uint64_t numBytes = 0;
McResult err = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_VERTEX_FLOAT, 0, NULL, &numBytes);

if (err != MC_NO_ERROR)
{
    // do stuff ...
}

uint32_t numberOfVertices = (uint32_t)(numBytes / (sizeof(float) * 3)); // <-- I think this is what you want 
```  

That should help. 

I will leave this issue open until I update the tutorial.

**Comment by chaojian-zhang** [comment]
Thanks for the reply. It totally makes sense now!
